<Project Sdk="Microsoft.NET.Sdk.Worker">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>dotnet-ServerMonitoring.Processor-a4dbcfcc-5210-4396-89c1-e89d6333e87b</UserSecretsId>
        <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.11" />
        <PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" Version="10.0.11" />
        <PackageReference Include="MongoDB.Driver" Version="3.11.1" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\ServerMonitoring.MessageQueue\ServerMonitoring.MessageQueue.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Content Include="..\.dockerignore">
        <Link>.dockerignore</Link>
      </Content>
    </ItemGroup>
</Project>
